name: Bug Report/反馈 bug
description: "如果你已经知道问题所在、怎么解决，请直接 提交 Pull Request 为社区做贡献，非常感谢。\n开发者也是人，也需要工作、休息、恋爱、陪伴家人、走亲会友等，也有心情不好和身体病痛，\n往往没有额外的时间精力顾及一些小问题，请理解和支持，开源要大家参与贡献才会更美好~\n少数个人的热情终有被耗尽的一天，只有大家共同建设和繁荣社区，才能让开源可持续发展！\n https://github.com/Tencent/APIJSON/issues/406 \n\n _________________________________ \n\n**提 bug 请发请求和响应的【完整截屏】，没图的自行解决！\n开发者有限的时间和精力主要放在【维护项目源码和文档】上！\n【描述不详细】 或 【文档/常见问题 已有答案】 的问题可能会被忽略！！\n【态度 不文明/不友善】的可能会被拉黑，问题也可能不予解答！！！**\n\n请求参数 JSON 中表名、字段名、关键词及对应的值都是大小写敏感、逗号敏感、分号敏感、空格敏感、换行敏感，\n大部分情况都不允许空格和换行，表名以大写字母开头，不要想当然，请严格按照 设计规范 来调用 API #181 \n\n1.尝试在 [常见问题](https://github.com/Tencent/APIJSON/issues/36) 和 [历史问题](https://github.com/TommyLemon/APIJSON/issues?q=is%3Aissue) 搜索答案。\n2.尝试阅读 [通用文档](https://github.com/TommyLemon/APIJSON/blob/master/Document.md) 或看 [视频教程](https://search.bilibili.com/all?keyword=APIJSON) 找到答案。\n3.尝试阅读 [Demo 示例代码](https://github.com/APIJSON/APIJSON-Demo/blob/master/APIJSON-Java-Server/APIJSONBoot-MultiDataSource/src/main/java/apijson/demo/DemoSQLConfig.java) 以找到答案。\n4.尝试自己 [检查或试验](http://apijson.cn/api) 以找到答案。\n5.尝试阅读 [源码和注释](https://github.com/Tencent/APIJSON/blob/master/APIJSONORM/src/main/java/apijson/orm/AbstractSQLConfig.java) 以找到答案。\n如果以上都尝试过了请填写以下模板提一个新的issue。\n强烈推荐阅读 [《如何向开源社区提问题》](https://github.com/seajs/seajs/issues/545)、[《如何有效地报告 Bug》](http://www.chiark.greenend.org.uk/~sgtatham/bugs-cn.html)、[《如何向开源项目提交无法解答的问题》](https://zhuanlan.zhihu.com/p/25795393)\n和 [《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)，更好的问题更容易获得帮助。"
title: "[Bug] "
labels: [kind/bug]
body:
- type: input
  attributes:
    label: APIJSON Version/APIJSON 版本号
    placeholder: |
      e.g./例如 5.4.0

  validations:
    required: true

- type: input
  attributes:
    label: DB type & Version/数据库类型及版本号
    placeholder: |
      e.g./例如 MySQL 5.7.34
        
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Environment/环境信息
    description: |
      e.g.
        - **OS/系统**: MacOS Monterey 12.6 (21G115) M1
        - **JDK/基础库**: 1.8.0_17
    value: |
        - OS/系统:
        - JDK/基础库:
    render: markdown

  validations:
    required: true

- type: textarea
  attributes:
    label: Current Behavior/问题描述
    description: A concise description of what you're experiencing. Attach screenshots if needed.
    render: markdown

  validations:
    required: true

- type: textarea
  attributes:
    label: Expected Behavior/期望结果
    description: A concise description of what you expected to happen.
    render: markdown

  validations:
    required: false


- type: textarea
  attributes:
    label: Any additional comments?/其它补充说明？
    description: |
      e.g. some background/context of how you ran into this bug./例如：一些背景或上下文信息，包括复现步骤、相关日志等
    render: markdown

  validations:
    required: false
