name: Bug Report/反馈 bug
description: Report a bug to APIJSON/为 APIJSON 反馈 bug
title: "[Bug] "
labels: [kind/bug]
body:
- type: input
  attributes:
    label: APIJSON Version/APIJSON 版本号
    placeholder: |
      e.g./例如 5.4.0

  validations:
    required: true

- type: input
  attributes:
    label: DB type & Version/数据库类型及版本号
    placeholder: |
      e.g./例如
        - MySQL 5.7.34
        
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Environment/环境信息
    description: |
      e.g.
        - **OS/系统**: MacOS Monterey 12.6 (21G115) M1
        - **JDK/基础库**: 1.8.0_17
    value: |
        - OS/系统:
        - JDK/基础库:
        - DB/数据库:
        - APIJSON:
    render: markdown

  validations:
    required: true

- type: textarea
  attributes:
    label: Current Behavior/问题描述
    description: A concise description of what you're experiencing. Attach screenshots if needed.
    render: markdown

  validations:
    required: true

- type: textarea
  attributes:
    label: Expected Behavior/期望结果
    description: A concise description of what you expected to happen.
    render: markdown

  validations:
    required: false


- type: textarea
  attributes:
    label: Any additional comments?/其它补充说明？
    description: |
      e.g. some background/context of how you ran into this bug./例如：一些背景或上下文信息，包括复现步骤、相关日志等
    render: markdown

  validations:
    required: false
